
from chess.exceptions import ValidationError


class MoveValidationError(ValidationError):
    pass

