
from chess.exceptions import ValidationError


class GameValidationError(ValidationError):
    pass

