class ArgumentError(Exception):
    pass


class BaseError(Exception):
    pass
